version: '3.1'

services:    
    web:
        build: .
        ports:
            - 3000:3000
        depends_on: 
            - db
        environment: 
            PROD_DATABASE_URL: postgres://postgres:example@db:5432/meeting-minutes
            PORT: 3000
    db:
        image: postgres
        restart: always
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example       
            POSTGRES_DB: meeting-minutes 
        ports:
            - 5432:5432

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    

     